<template>
  <div class="language-picker">
    <div class="lang-container">
      
      <div
        class="lang-selected"
        @click="toggleLanguagePicker">
        <div class="selected-lang-container">
          <img class="flag-icon" :src="flags[selectedLang?.code || 'en-US']" />
          <div class="lang-text">{{ selectedLang?.codeShort || 'EN' }}</div>
        </div>
      </div>
      
      <div
        v-if="openState"
        class="lang-menu">
        <div
          v-ripple
          v-for="lang in languages"
          :key="`${lang.code}`"
          class="lang-item"
          @click="selectLang(lang)">
          <div class="lang-flag">
            <img
              class="flag-icon" 
              :src="flags[lang.code]" />
          </div>
          <div class="lang-text">
            {{ lang.codeShort }}
          </div>
        </div>
      </div>
      
    </div>
  </div>
</template>

<script setup>
  import { onMounted, ref } from 'vue'
  import i18next from 'i18next'
  
  import stores from '@/stores/index.js'
  
  import { asyncComponents } from '@/utils/helpers'
  import flags from '@/utils/helpers/flagLoader'

  const localizationStore = stores.localizationStore()
  const toastStore = stores.ui.toastStore()

  const selectedLang = ref('en')
  const openState = ref(false)
  const firstSelect = ref(true)
  const languages = ref([
    { code: 'en-US', codeShort: 'en', name: 'English' },
    { code: 'de-DE', codeShort: 'de', name: 'Deutsch' },
    { code: 'es-ES', codeShort: 'es', name: 'Español' },
    { code: 'fr-FR', codeShort: 'fr', name: 'Français' },
    { code: 'it-IT', codeShort: 'it', name: 'Italiano' },
    { code: 'ja-JP', codeShort: 'ja', name: '日本語' },
    { code: 'ko-KR', codeShort: 'ko', name: '한국어' },
    { code: 'ru-RU', codeShort: 'ru', name: 'Русский' },
    { code: 'zh-CN', codeShort: 'zh', name: '中文' }
  ])

  onMounted(() => {
    selectedLang.value = languages.value.find(lang => lang.code === localizationStore.currentLang) || languages.value[0]
  })

  const toggleLanguagePicker = () => {
    openState.value = !openState.value
  }

  const selectLang = (lang) => {
    localizationStore.changeLanguage(lang.code)
    selectedLang.value = lang

    if (firstSelect.value) {
      firstSelect.value = false

      toastStore.addToast({
        component: asyncComponents.ToastMessage,
        persist: true,
        data: {
          type: 'warning',
          // title: 'Language Changed',
          title: i18next.t('components:LANGUAGE_PICKER.TOASTS.LANGUAGE_CHANGED.DESC', { lng: lang.name }),
          message: i18next.t('components:LANGUAGE_PICKER.TOASTS.LANGUAGE_CHANGED.TITLE', { lng: lang.name })
        }
      })
    }

    setTimeout(() => {
      openState.value = false
    }, 200)
  }
// 'Translations are generated by AI and may not be perfect.'
</script>
